# WINDOW SIZE
WIDTH = 1200
HEIGHT = 700

SCALE = 4
SPEED = 3


# BOARD SIZE
BOARD_WIDTH = 150 * SCALE 
BOARD_HEIGHT = 39 * SCALE
BOTTOM_TUNNEL_HEIGHT = 4 * SCALE
TOP_TUNNEL_HEIGHT = 12 * SCALE
PATH_WIDTH = 2 * SCALE
PATH_HEIGHT = 23 * SCALE

MARGIN = 30 * SCALE


#EXIT -- bottom left of board
EXIT_WIDTH = 1 * SCALE
EXIT_HEIGHT = 4 * SCALE
EXIT_X = 0
EXIT_Y = BOARD_HEIGHT


#BUS POSITION
BUS_TOP_LEFT_X = BOARD_WIDTH // 2
BUS_TOP_LEFT_Y = TOP_TUNNEL_HEIGHT // 2
BUS_LENGTH = 3 * SCALE
BUS_WIDTH = SCALE

BUS_EXIT_BUFFOR = 4
EVACUATORS = 25 * BUS_EXIT_BUFFOR


#COLORS
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0)


#LOGIC VALUES
ALFA = 1 #DYNAMIC
BETA = 0.001 #STATIC
DYNAMIC_INCREMENT = 5 * SPEED